// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: user.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	UserPasswordSignInReq
	UserPasswordSignInRsp
	GetUserInfoReq
	GetUserInfoRsp
	CheckUserTokenReq
	CheckUserTokenRsp
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for User service

type UserService interface {
	UserPasswordSignIn(ctx context.Context, in *UserPasswordSignInReq, opts ...client.CallOption) (*UserPasswordSignInRsp, error)
	GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...client.CallOption) (*GetUserInfoRsp, error)
	CheckUserToken(ctx context.Context, in *CheckUserTokenReq, opts ...client.CallOption) (*CheckUserTokenRsp, error)
}

type userService struct {
	c           client.Client
	serviceName string
}

func UserServiceClient(serviceName string, c client.Client) UserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "user"
	}
	return &userService{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *userService) UserPasswordSignIn(ctx context.Context, in *UserPasswordSignInReq, opts ...client.CallOption) (*UserPasswordSignInRsp, error) {
	req := c.c.NewRequest(c.serviceName, "User.UserPasswordSignIn", in)
	out := new(UserPasswordSignInRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...client.CallOption) (*GetUserInfoRsp, error) {
	req := c.c.NewRequest(c.serviceName, "User.GetUserInfo", in)
	out := new(GetUserInfoRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) CheckUserToken(ctx context.Context, in *CheckUserTokenReq, opts ...client.CallOption) (*CheckUserTokenRsp, error) {
	req := c.c.NewRequest(c.serviceName, "User.CheckUserToken", in)
	out := new(CheckUserTokenRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserHandler interface {
	UserPasswordSignIn(context.Context, *UserPasswordSignInReq, *UserPasswordSignInRsp) error
	GetUserInfo(context.Context, *GetUserInfoReq, *GetUserInfoRsp) error
	CheckUserToken(context.Context, *CheckUserTokenReq, *CheckUserTokenRsp) error
}

func RegisterUserHandler(s server.Server, hdlr UserHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&User{hdlr}, opts...))
}

type User struct {
	UserHandler
}

func (h *User) UserPasswordSignIn(ctx context.Context, in *UserPasswordSignInReq, out *UserPasswordSignInRsp) error {
	return h.UserHandler.UserPasswordSignIn(ctx, in, out)
}

func (h *User) GetUserInfo(ctx context.Context, in *GetUserInfoReq, out *GetUserInfoRsp) error {
	return h.UserHandler.GetUserInfo(ctx, in, out)
}

func (h *User) CheckUserToken(ctx context.Context, in *CheckUserTokenReq, out *CheckUserTokenRsp) error {
	return h.UserHandler.CheckUserToken(ctx, in, out)
}
