// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserPasswordSignInReq struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserPasswordSignInReq) Reset()         { *m = UserPasswordSignInReq{} }
func (m *UserPasswordSignInReq) String() string { return proto.CompactTextString(m) }
func (*UserPasswordSignInReq) ProtoMessage()    {}
func (*UserPasswordSignInReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserPasswordSignInReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPasswordSignInReq.Unmarshal(m, b)
}
func (m *UserPasswordSignInReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPasswordSignInReq.Marshal(b, m, deterministic)
}
func (m *UserPasswordSignInReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPasswordSignInReq.Merge(m, src)
}
func (m *UserPasswordSignInReq) XXX_Size() int {
	return xxx_messageInfo_UserPasswordSignInReq.Size(m)
}
func (m *UserPasswordSignInReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPasswordSignInReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserPasswordSignInReq proto.InternalMessageInfo

func (m *UserPasswordSignInReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UserPasswordSignInReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserPasswordSignInRsp struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Result               bool     `protobuf:"varint,4,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserPasswordSignInRsp) Reset()         { *m = UserPasswordSignInRsp{} }
func (m *UserPasswordSignInRsp) String() string { return proto.CompactTextString(m) }
func (*UserPasswordSignInRsp) ProtoMessage()    {}
func (*UserPasswordSignInRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserPasswordSignInRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPasswordSignInRsp.Unmarshal(m, b)
}
func (m *UserPasswordSignInRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPasswordSignInRsp.Marshal(b, m, deterministic)
}
func (m *UserPasswordSignInRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPasswordSignInRsp.Merge(m, src)
}
func (m *UserPasswordSignInRsp) XXX_Size() int {
	return xxx_messageInfo_UserPasswordSignInRsp.Size(m)
}
func (m *UserPasswordSignInRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPasswordSignInRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UserPasswordSignInRsp proto.InternalMessageInfo

func (m *UserPasswordSignInRsp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UserPasswordSignInRsp) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UserPasswordSignInRsp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserPasswordSignInRsp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type GetUserInfoReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionKey           string   `protobuf:"bytes,2,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoReq) Reset()         { *m = GetUserInfoReq{} }
func (m *GetUserInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoReq) ProtoMessage()    {}
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *GetUserInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoReq.Unmarshal(m, b)
}
func (m *GetUserInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoReq.Marshal(b, m, deterministic)
}
func (m *GetUserInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoReq.Merge(m, src)
}
func (m *GetUserInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoReq.Size(m)
}
func (m *GetUserInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoReq proto.InternalMessageInfo

func (m *GetUserInfoReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetUserInfoReq) GetSessionKey() string {
	if m != nil {
		return m.SessionKey
	}
	return ""
}

type GetUserInfoRsp struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserDisplayName      string   `protobuf:"bytes,2,opt,name=user_display_name,json=userDisplayName,proto3" json:"user_display_name,omitempty"`
	Gender               string   `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Mobile               string   `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Signature            string   `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	City                 string   `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	Province             string   `protobuf:"bytes,7,opt,name=province,proto3" json:"province,omitempty"`
	Country              string   `protobuf:"bytes,8,opt,name=country,proto3" json:"country,omitempty"`
	Language             string   `protobuf:"bytes,9,opt,name=language,proto3" json:"language,omitempty"`
	Email                string   `protobuf:"bytes,10,opt,name=email,proto3" json:"email,omitempty"`
	HasUnionId           bool     `protobuf:"varint,11,opt,name=has_union_id,json=hasUnionId,proto3" json:"has_union_id,omitempty"`
	Avatar               string   `protobuf:"bytes,12,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Logo                 string   `protobuf:"bytes,13,opt,name=logo,proto3" json:"logo,omitempty"`
	RewardCode           string   `protobuf:"bytes,14,opt,name=reward_code,json=rewardCode,proto3" json:"reward_code,omitempty"`
	UserId               int64    `protobuf:"varint,15,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string   `protobuf:"bytes,16,opt,name=name,proto3" json:"name,omitempty"`
	Corporation          string   `protobuf:"bytes,17,opt,name=corporation,proto3" json:"corporation,omitempty"`
	Position             string   `protobuf:"bytes,18,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoRsp) Reset()         { *m = GetUserInfoRsp{} }
func (m *GetUserInfoRsp) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoRsp) ProtoMessage()    {}
func (*GetUserInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *GetUserInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoRsp.Unmarshal(m, b)
}
func (m *GetUserInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoRsp.Marshal(b, m, deterministic)
}
func (m *GetUserInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoRsp.Merge(m, src)
}
func (m *GetUserInfoRsp) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoRsp.Size(m)
}
func (m *GetUserInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoRsp proto.InternalMessageInfo

func (m *GetUserInfoRsp) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *GetUserInfoRsp) GetUserDisplayName() string {
	if m != nil {
		return m.UserDisplayName
	}
	return ""
}

func (m *GetUserInfoRsp) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *GetUserInfoRsp) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *GetUserInfoRsp) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *GetUserInfoRsp) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *GetUserInfoRsp) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *GetUserInfoRsp) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *GetUserInfoRsp) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *GetUserInfoRsp) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetUserInfoRsp) GetHasUnionId() bool {
	if m != nil {
		return m.HasUnionId
	}
	return false
}

func (m *GetUserInfoRsp) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *GetUserInfoRsp) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *GetUserInfoRsp) GetRewardCode() string {
	if m != nil {
		return m.RewardCode
	}
	return ""
}

func (m *GetUserInfoRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetUserInfoRsp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetUserInfoRsp) GetCorporation() string {
	if m != nil {
		return m.Corporation
	}
	return ""
}

func (m *GetUserInfoRsp) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

type CheckUserTokenReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUserTokenReq) Reset()         { *m = CheckUserTokenReq{} }
func (m *CheckUserTokenReq) String() string { return proto.CompactTextString(m) }
func (*CheckUserTokenReq) ProtoMessage()    {}
func (*CheckUserTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *CheckUserTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUserTokenReq.Unmarshal(m, b)
}
func (m *CheckUserTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUserTokenReq.Marshal(b, m, deterministic)
}
func (m *CheckUserTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUserTokenReq.Merge(m, src)
}
func (m *CheckUserTokenReq) XXX_Size() int {
	return xxx_messageInfo_CheckUserTokenReq.Size(m)
}
func (m *CheckUserTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUserTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUserTokenReq proto.InternalMessageInfo

func (m *CheckUserTokenReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CheckUserTokenRsp struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InstId               string   `protobuf:"bytes,3,opt,name=inst_id,json=instId,proto3" json:"inst_id,omitempty"`
	Mobile               string   `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUserTokenRsp) Reset()         { *m = CheckUserTokenRsp{} }
func (m *CheckUserTokenRsp) String() string { return proto.CompactTextString(m) }
func (*CheckUserTokenRsp) ProtoMessage()    {}
func (*CheckUserTokenRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *CheckUserTokenRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUserTokenRsp.Unmarshal(m, b)
}
func (m *CheckUserTokenRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUserTokenRsp.Marshal(b, m, deterministic)
}
func (m *CheckUserTokenRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUserTokenRsp.Merge(m, src)
}
func (m *CheckUserTokenRsp) XXX_Size() int {
	return xxx_messageInfo_CheckUserTokenRsp.Size(m)
}
func (m *CheckUserTokenRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUserTokenRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUserTokenRsp proto.InternalMessageInfo

func (m *CheckUserTokenRsp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *CheckUserTokenRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CheckUserTokenRsp) GetInstId() string {
	if m != nil {
		return m.InstId
	}
	return ""
}

func (m *CheckUserTokenRsp) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func init() {
	proto.RegisterType((*UserPasswordSignInReq)(nil), "user.UserPasswordSignInReq")
	proto.RegisterType((*UserPasswordSignInRsp)(nil), "user.UserPasswordSignInRsp")
	proto.RegisterType((*GetUserInfoReq)(nil), "user.GetUserInfoReq")
	proto.RegisterType((*GetUserInfoRsp)(nil), "user.GetUserInfoRsp")
	proto.RegisterType((*CheckUserTokenReq)(nil), "user.CheckUserTokenReq")
	proto.RegisterType((*CheckUserTokenRsp)(nil), "user.CheckUserTokenRsp")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 544 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0x4b, 0x6f, 0xdb, 0x3c,
	0x10, 0xfc, 0xfc, 0x88, 0x1f, 0xeb, 0x7c, 0x4e, 0x4d, 0xa4, 0x35, 0xe1, 0x14, 0xa8, 0xa1, 0x53,
	0xda, 0x43, 0x0e, 0xed, 0xb1, 0xc7, 0x04, 0x28, 0xdc, 0x00, 0x41, 0xe0, 0x36, 0x67, 0x83, 0x91,
	0xb6, 0x32, 0x61, 0x99, 0x54, 0x48, 0x29, 0x81, 0x7e, 0x6b, 0x7f, 0x4b, 0x81, 0x62, 0x49, 0xba,
	0x95, 0x60, 0xf5, 0xc6, 0xd9, 0xa1, 0xf6, 0x31, 0x3b, 0x14, 0x40, 0x69, 0xd1, 0x5c, 0xe5, 0x46,
	0x17, 0x9a, 0xf5, 0xe9, 0x1c, 0xdd, 0xc2, 0xeb, 0x07, 0x8b, 0xe6, 0x5e, 0x58, 0xfb, 0xa2, 0x4d,
	0xf2, 0x4d, 0xa6, 0x6a, 0xa5, 0xd6, 0xf8, 0xc4, 0xde, 0xc0, 0x60, 0xaf, 0x1f, 0x65, 0x86, 0xbc,
	0xb3, 0xec, 0x5c, 0x8e, 0xd7, 0x01, 0xb1, 0x05, 0x8c, 0xf2, 0x70, 0x99, 0x77, 0x1d, 0xf3, 0x07,
	0x47, 0x4f, 0xad, 0xc9, 0x6c, 0xce, 0xce, 0xe1, 0xa4, 0xd0, 0x3b, 0x54, 0x21, 0x97, 0x07, 0xb5,
	0x12, 0xdd, 0x46, 0x09, 0x06, 0x7d, 0x25, 0xf6, 0xc8, 0x7b, 0x2e, 0xea, 0xce, 0x74, 0xd7, 0xa0,
	0x2d, 0xb3, 0x82, 0xf7, 0x97, 0x9d, 0xcb, 0xd1, 0x3a, 0xa0, 0xe8, 0x2b, 0x4c, 0xbf, 0x60, 0x41,
	0x55, 0x57, 0xea, 0x87, 0xa6, 0xc6, 0xe7, 0x30, 0xa4, 0xc9, 0x36, 0x32, 0x71, 0xd5, 0x7a, 0xeb,
	0x01, 0xc1, 0x55, 0xc2, 0xde, 0xc1, 0xc4, 0xa2, 0xb5, 0x52, 0xab, 0xcd, 0x0e, 0xab, 0x50, 0x13,
	0x42, 0xe8, 0x16, 0xab, 0xe8, 0x57, 0xaf, 0x99, 0xcc, 0xe6, 0xec, 0x02, 0xc6, 0x2e, 0x99, 0xeb,
	0xc7, 0x37, 0x3f, 0xa2, 0xc0, 0x1d, 0xf5, 0xf4, 0x01, 0x66, 0x8e, 0x4c, 0xa4, 0xcd, 0x33, 0x51,
	0xf9, 0x4b, 0x3e, 0xed, 0x19, 0x11, 0x37, 0x3e, 0x7e, 0x17, 0xfa, 0x4f, 0x51, 0x25, 0x68, 0xc2,
	0x54, 0x01, 0xd5, 0x34, 0xe8, 0x37, 0x34, 0x78, 0x0b, 0x63, 0x2b, 0x53, 0x25, 0x8a, 0xd2, 0x20,
	0x3f, 0x71, 0xd4, 0xdf, 0x00, 0x29, 0x14, 0xcb, 0xa2, 0xe2, 0x03, 0xaf, 0x10, 0x9d, 0xdd, 0x62,
	0x8c, 0x7e, 0x96, 0x2a, 0x46, 0x3e, 0x0c, 0x8b, 0x09, 0x98, 0x71, 0x18, 0xc6, 0xba, 0x54, 0x85,
	0xa9, 0xf8, 0xc8, 0x51, 0x07, 0x48, 0x5f, 0x65, 0x42, 0xa5, 0xa5, 0x48, 0x91, 0x8f, 0xfd, 0x57,
	0x07, 0x4c, 0x5b, 0xc3, 0xbd, 0x90, 0x19, 0x07, 0xbf, 0x35, 0x07, 0xd8, 0x12, 0x4e, 0xb7, 0xc2,
	0x6e, 0x4a, 0x45, 0x42, 0xca, 0x84, 0x4f, 0xdc, 0x3e, 0x60, 0x2b, 0xec, 0x03, 0x85, 0x56, 0x09,
	0xcd, 0x24, 0x9e, 0x45, 0x21, 0x0c, 0x3f, 0xf5, 0x33, 0x79, 0x44, 0x5d, 0x67, 0x3a, 0xd5, 0xfc,
	0x7f, 0xdf, 0x35, 0x9d, 0x69, 0x29, 0x06, 0x5f, 0x84, 0x49, 0x36, 0xb1, 0x4e, 0x90, 0x4f, 0xfd,
	0x52, 0x7c, 0xe8, 0x5a, 0x27, 0x58, 0x5f, 0xe7, 0x59, 0x63, 0x9d, 0x07, 0x97, 0xbc, 0xaa, 0xb9,
	0x64, 0x09, 0x93, 0x58, 0x9b, 0x5c, 0x1b, 0x51, 0x48, 0xad, 0xf8, 0xcc, 0x51, 0xf5, 0x90, 0x53,
	0x49, 0x5b, 0xe9, 0x68, 0x16, 0x54, 0x0a, 0x38, 0x7a, 0x0f, 0xb3, 0xeb, 0x2d, 0xc6, 0x3b, 0x32,
	0xc0, 0x77, 0x72, 0x28, 0xd9, 0xa9, 0xd5, 0xba, 0x51, 0x79, 0x74, 0xd5, 0xe6, 0x35, 0x8f, 0x76,
	0xea, 0x1e, 0xad, 0x8f, 0xd0, 0x6d, 0x8c, 0x30, 0x87, 0xa1, 0x54, 0xb6, 0x20, 0x22, 0xb8, 0x82,
	0xa0, 0x57, 0xb0, 0xcd, 0x15, 0x1f, 0x7f, 0x76, 0xa0, 0x4f, 0x25, 0xd9, 0x3d, 0xb0, 0xe3, 0x97,
	0xc6, 0x2e, 0xae, 0xdc, 0xfb, 0x6e, 0x7d, 0xd0, 0x8b, 0x7f, 0x93, 0x36, 0x8f, 0xfe, 0x63, 0x9f,
	0x61, 0x52, 0xf3, 0x3e, 0x3b, 0xf7, 0xb7, 0x9b, 0x6f, 0x6b, 0xd1, 0x12, 0x75, 0x1f, 0xdf, 0xc0,
	0xb4, 0x29, 0x07, 0x9b, 0xfb, 0x9b, 0x47, 0x7a, 0x2e, 0xda, 0x09, 0xca, 0xf2, 0x38, 0x70, 0x3f,
	0xa6, 0x4f, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x25, 0x05, 0x40, 0x1d, 0xa6, 0x04, 0x00, 0x00,
}
